spring:
  datasource:
    hikari:
      maximum-pool-size: 2
      idle-timeout: 60000
      max-lifetime: 300000
      connection-test-query: "SELECT 1"
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000

custom:
  app:
    cors-allowed-origins:
      - https://dev.spotit.co.kr
      - http://localhost:3000
