spring:
  datasource:
    hikari:
      maximum-pool-size: 2
      idle-timeout: 60000
      max-lifetime: 300000
      connection-test-query: "SELECT 1"
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000

# Swagger 설정 (개발 환경에서만 활성화)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

custom:
  app:
    cors-allowed-origins: ${CORS_ALLOWED_ORIGINS}
