name: Deploy Backend to Production

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  IMAGE_NAME: spotit-backend
  PROJECT_NAME: spotit

jobs:
  deploy:
    name: Deploy to Production EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build test
        working-directory: ./backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy on Production EC2 with Blue-Green
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}/${{ env.PROJECT_NAME }}

            # Login to Docker Hub to pull private packages
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Create .env file for docker-compose
            echo "IMAGE_TAG=${{ github.sha }}" > .env
            echo "IMAGE_REGISTRY=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}" >> .env

            # 새 이미지 pull
            docker compose pull backend-blue backend-green

            # Blue-Green 배포 스크립트 실행
            chmod +x deploy.sh
            ./deploy.sh

            # 배포 결과 확인
            if [ $? -eq 0 ]; then
              echo "✅ Blue-Green 배포 성공"
            else
              echo "❌ Blue-Green 배포 실패"
              exit 1
            fi
