name: Issue Notification

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            {
              "embeds": [
                {
                  "title": "🎯 새로운 이슈가 생성되었습니다",
                  "color": 3447003,
                  "fields": [
                    {
                      "name": "이슈 제목",
                      "value": "${{ github.event.issue.title }}",
                      "inline": false
                    },
                    {
                      "name": "작성자",
                      "value": "${{ github.event.issue.user.login }}",
                      "inline": true
                    },
                    {
                      "name": "라벨",
                      "value": "${{ join(github.event.issue.labels.*.name, ', ') }}",
                      "inline": true
                    }
                  ],
                  "description": "${{ github.event.issue.body }}",
                  "url": "${{ github.event.issue.html_url }}",
                  "footer": {
                    "text": "JECT 3기 6팀"
                  },
                  "timestamp": "${{ github.event.issue.created_at }}"
                }
              ]
            } 