name: Mirror to Fork (main & develop)

on:
  push:
    branches: [main, develop]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # 기본 GITHUB_TOKEN 제거

      - name: Set git identity
        run: |
          git config user.name "spotit-ci"
          git config user.email "spotit-ci@users.noreply.github.com"

      - name: Auth with PAT via header & add fork remote (full URL)
        env:
          TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}   # spotit-developer 계정의 Fine-grained PAT
        run: |
          # 혹시 남아있을 수 있는 기본 인증 헤더 제거
          git config --global http.https://github.com/.extraheader ""
          # PAT을 Authorization 헤더로 주입 (basic: x-access-token:<PAT>)
          AUTH=$(printf "x-access-token:%s" "$TOKEN" | base64)
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $AUTH"

          # 포크 레포 풀 URL 고정
          git remote add fork https://github.com/spotit-developer/JECT-3th-6team.git
          git remote -v

          # 접근 권한 확인 (실패 시 토큰/권한 문제)
          git ls-remote fork

      - name: Push current branch to fork
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git push fork ${BRANCH}:${BRANCH}
          # 히스토리 불일치로 막히면 아래 줄로 강제 동기화(주의)
          # git push fork ${BRANCH}:${BRANCH} --force
