name: Mirror to Fork (main & develop)

on:
  push:
    branches: [main, develop]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # 기본 GITHUB_TOKEN 제거

      - name: Set git identity
        run: |
          git config user.name "spotit-ci"
          git config user.email "spotit-ci@users.noreply.github.com"

      - name: Add fork remote (full URL with token)
        env:
          TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}   # spotit-developer 계정 PAT
        run: |
          # 혹시 기본 extraheader 남아있을 경우 제거
          git config --global http.https://github.com/.extraheader ""
          # 포크 레포 주소 + PAT으로 remote 추가
          git remote add fork https://x-access-token:${TOKEN}@github.com/spotit-developer/JECT-3th-6team.git
          git remote -v
          # 권한/접근 테스트
          git ls-remote fork

      - name: Push current branch to fork
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git push fork ${BRANCH}:${BRANCH}
          # 필요시 강제 동기화 (히스토리 불일치일 때만)
          # git push fork ${BRANCH}:${BRANCH} --force
