name: Mirror to Fork (main & develop)

on:
  push:
    branches: [main, develop]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  mirror:
    # ✅ 포크 레포가 아니고 + 토큰이 env로 주입되어 있을 때만 실행
    if: ${{ !github.event.repository.fork && env.HAS_TOKEN != '' }}
    runs-on: ubuntu-latest

    # secrets를 env로 매핑 → if에서 env로 체크
    env:
      HAS_TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}

    steps:
      - name: Checkout (full history, no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Debug info
        env:
          BRANCH: ${{ github.ref_name }}
          TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}
        run: |
          echo "==== DEBUG INFO ===="
          echo "Current branch: $BRANCH"
          if [ -z "$TOKEN" ]; then
            echo "❌ Token is EMPTY (check Actions Secrets!)"
            exit 1
          else
            echo "✅ Token is present (masked in logs)"
          fi
          git --version

      - name: Set git identity
        run: |
          git config user.name "spotit-ci"
          git config user.email "spotit-ci@users.noreply.github.com"

      - name: Add fork remote (Classic PAT with username in URL)
        env:
          TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}   # Classic PAT (scopes: repo + workflow)
        run: |
          # 기존 extraheader 제거
          git config --global http.https://github.com/.extraheader ""
          # 포크 레포 풀 URL + PAT 인증
          git remote add fork https://spotit-developer:${TOKEN}@github.com/spotit-developer/JECT-3th-6team.git
          echo "==== REMOTE INFO ===="
          git remote -v
          echo "====================="
          # 접근 권한 확인
          git ls-remote fork

      - name: Push current branch to fork
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "==== PUSHING $BRANCH ===="
          git push fork ${BRANCH}:${BRANCH}
          # 히스토리 불일치/브랜치 보호 규칙 시 필요하면:
          # git push fork ${BRANCH}:${BRANCH} --force-with-lease
