name: Mirror to Fork (main & develop)

on:
  push:
    branches: [main, develop]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false    # ✅ 기본 GITHUB_TOKEN 제거

      - name: Set git identity
        run: |
          git config user.name "spotit-ci"
          git config user.email "spotit-ci@users.noreply.github.com"

      - name: Prepare PAT remote
        env:
          TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}   # ✅ 팀 계정 PAT
          FORK_OWNER: ${{ vars.FORK_OWNER }}      # 예: team-account
          FORK_REPO:  ${{ vars.FORK_REPO }}       # 예: spotit
        run: |
          # 혹시 남아있을 수 있는 기본 토큰 헤더 제거(안전빵)
          git config --global http.https://github.com/.extraheader ""
          # PAT로 fork remote 추가
          git remote add fork https://x-access-token:${TOKEN}@github.com/${FORK_OWNER}/${FORK_REPO}.git
          git remote -v
          # 권한 체크(실패하면 바로 원인 파악 쉬움)
          git ls-remote fork

      - name: Push current branch to fork
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git push fork ${BRANCH}:${BRANCH}
          # 필요 시 강제 동기화(히스토리 어긋났을 때만 사용)
          # git push fork ${BRANCH}:${BRANCH} --force
