name: PR Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  jjeongsu: ${{secrets.JJEONGSU_DISCORD_ID}}
  kimhyunjee: ${{secrets.KIMHYUNJEE_DISCORD_ID}}
  robinjoon: ${{secrets.ROBINJON_DISCORD_ID}}
  sangxxjin: ${{secrets.SANGXXJIN_DISCORD_ID}}
  

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get Assignees
        id: assignees
        run: |
          # PR 작성자의 Discord ID 설정
          echo "ASSIGNEE_DISCORD_ID=${{ env[github.event.pull_request.user.login] }}" >> $GITHUB_ENV
          
          # 모든 리뷰어의 Discord ID를 쉼표로 구분하여 설정
          REVIEWERS=""
          for reviewer in ${{ join(github.event.pull_request.requested_reviewers.*.login, ' ') }}; do
            if [ -n "$REVIEWERS" ]; then
              REVIEWERS="$REVIEWERS,"
            fi
            REVIEWERS="$REVIEWERS${{ env[reviewer] }}"
          done
          echo "REVIEWER_DISCORD_IDS=$REVIEWERS" >> $GITHUB_ENV

      - name: Get PR information
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            // Get project information using GraphQL API
            const query = `
              query($owner: String!, $repo: String!, $prNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $prNumber) {
                    projectItems(first: 1) {
                      nodes {
                        project {
                          title
                        }
                        fieldValues(first: 10) {
                          nodes {
                            ... on ProjectV2ItemFieldDateValue {
                              date
                              field {
                                ... on ProjectV2Field {
                                  name
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const variables = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              prNumber: pr.number
            };
            
            const response = await github.graphql(query, variables);
            const projectItem = response.repository.pullRequest.projectItems.nodes[0];
            
            if (!projectItem) {
              return {
                review_due_date: 'Not set',
                merge_due_date: 'Not set'
              };
            }
            
            const fields = projectItem.fieldValues.nodes;
            const reviewDueDate = fields.find(field => 
              field?.field?.name === '리뷰 마감일'
            )?.date || 'Not set';
            
            const mergeDueDate = fields.find(field => 
              field?.field?.name === '머지 예정일'
            )?.date || 'Not set';
            
            return {
              review_due_date: reviewDueDate,
              merge_due_date: mergeDueDate
            };

      - name: Send Discord notification
        uses: actions/github-script@v7
        with:
          script: |
            // 모든 리뷰어 멘션 생성
            const reviewerIds = process.env.REVIEWER_DISCORD_IDS ? 
              process.env.REVIEWER_DISCORD_IDS.split(',').map(id => `<@${id}>`).join(', ') : 
              '리뷰어가 지정되지 않았습니다.';
            
            const authorMention = `<@${process.env.ASSIGNEE_DISCORD_ID}>`;
            
            const message = {
              embeds: [{
                title: "${{ github.event.pull_request.title }}",
                url: "${{ github.event.pull_request.html_url }}",
                color: 0x5865F2,
                fields: [
                  {
                    name: 'Review Request',
                    value: `${reviewerIds}님 ${authorMention}의 리뷰 요청이 있습니다.`
                  },
                  {
                    name: 'Review Due Date',
                    value: '${{ steps.pr_info.outputs.review_due_date }}'
                  },
                  {
                    name: 'Merge Due Date',
                    value: '${{ steps.pr_info.outputs.merge_due_date }}'
                  }
                ]
              }]
            };
            
            await fetch(process.env.DISCORD_WEBHOOK_URL, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify(message),
            });
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}