name: PR Review Notification

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Discord notification
        uses: actions/github-script@v7
        with:
          script: |
            const review = context.payload.review;
            const pr = context.payload.pull_request;
            
            // Get GitHub to Discord ID mapping from secrets
            let idMapping = {};
            let authorReviewerMapping = {};
            
            console.log('USERNAME_DISCORD_MAPPING:', process.env.USERNAME_DISCORD_MAPPING);
            try {
              if (!process.env.USERNAME_DISCORD_MAPPING) {
                throw new Error('USERNAME_DISCORD_MAPPING 시크릿이 설정되지 않았습니다.');
              }
              // 쉼표로 구분된 매핑 문자열을 파싱
              const mappings = process.env.USERNAME_DISCORD_MAPPING.split(',');
              for (const mapping of mappings) {
                const [githubUsername, discordId] = mapping.split(':').map(s => s.trim());
                if (githubUsername && discordId) {
                  idMapping[githubUsername] = discordId;
                }
              }
              if (Object.keys(idMapping).length === 0) {
                throw new Error('USERNAME_DISCORD_MAPPING이 올바른 형식이 아닙니다.');
              }
            } catch (error) {
              console.error('시크릿 파싱 에러:', error.message);
              throw new Error(`시크릿 파싱 에러: ${error.message}`);
            }
            
            console.log('AUTHOR_REVIEWER_MAPPING:', process.env.AUTHOR_REVIEWER_MAPPING);
            try {
              if (!process.env.AUTHOR_REVIEWER_MAPPING) {
                throw new Error('AUTHOR_REVIEWER_MAPPING 시크릿이 설정되지 않았습니다.');
              }
              // 쉼표로 구분된 매핑 문자열을 파싱
              const mappings = process.env.AUTHOR_REVIEWER_MAPPING.split(',');
              for (const mapping of mappings) {
                const [author, reviewer] = mapping.split(':').map(s => s.trim());
                if (author && reviewer) {
                  authorReviewerMapping[author] = reviewer;
                }
              }
              if (Object.keys(authorReviewerMapping).length === 0) {
                throw new Error('AUTHOR_REVIEWER_MAPPING이 올바른 형식이 아닙니다.');
              }
            } catch (error) {
              console.error('시크릿 파싱 에러:', error.message);
              throw new Error(`시크릿 파싱 에러: ${error.message}`);
            }
            
            // Get Discord IDs
            const assigneeDiscordId = idMapping[pr.assignee?.login] || pr.assignee?.login;
            const reviewerDiscordId = idMapping[review.user.login] || review.user.login;
            
            const assigneeMention = assigneeDiscordId ? `<@${assigneeDiscordId}>` : 'PR 작성자';
            const reviewerMention = `<@${reviewerDiscordId}>`;
            
            // 리뷰 상태에 따른 이모지
            const stateEmoji = {
              APPROVED: '✅',
              CHANGES_REQUESTED: '❌',
              COMMENTED: '💬'
            };
            
            const message = {
              embeds: [{
                title: `PR 리뷰 알림 ${stateEmoji[review.state]}`,
                url: review.html_url,
                color: review.state === 'APPROVED' ? 0x57F287 : 
                       review.state === 'CHANGES_REQUESTED' ? 0xED4245 : 0x5865F2,
                fields: [
                  {
                    name: '리뷰 상태',
                    value: review.state === 'APPROVED' ? '승인' :
                           review.state === 'CHANGES_REQUESTED' ? '변경 요청' : '코멘트'
                  },
                  {
                    name: '리뷰 내용',
                    value: review.body || '리뷰 내용이 없습니다.'
                  }
                ],
                description: `${assigneeMention}님 ${reviewerMention}님의 리뷰가 작성되었습니다.`
              }]
            };
            
            await fetch(process.env.DISCORD_WEBHOOK_URL, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify(message),
            });
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          USERNAME_DISCORD_MAPPING: ${{ secrets.USERNAME_DISCORD_MAPPING }}
          AUTHOR_REVIEWER_MAPPING: ${{ secrets.AUTHOR_REVIEWER_MAPPING }} 